name: fyp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  path: ^1.8.3
  async: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/dumbbell.jpg
    - assets/taskManager.jpg
    - assets/mealPlanning.jpg
    - assets/Fitness&Exercise.jpg
    - assets/Breakfast.jpg
    - assets/Meal.jpg
    - assets/Dinner.jpg
