name: fyp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.9
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  path: ^1.8.3
  async: ^2.12.0
  table_calendar: ^3.0.9
  reorderables: ^0.6.0
  provider: ^6.0.5
  cached_network_image: ^3.3.0
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/dumbbell.jpg
    - assets/taskManager.jpg
    - assets/mealPlanning.jpg
    - assets/Fitness&Exercise.jpg
    - assets/Breakfast.jpg
    - assets/Meal.jpg
    - assets/Dinner.jpg
